require("andromeda.plugins.flash")
require("andromeda.plugins.fugitive")
require("andromeda.plugins.gitgutter")
require("andromeda.plugins.harpoon")
require("andromeda.plugins.lualine")
require("andromeda.plugins.mason")
require("andromeda.plugins.signify")
require("andromeda.plugins.telescope")
